version: '3.8'

services:
  mongo:
    image: mongo:7.0-rc
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
  redis:
    image: 'redis:7.2.0'
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  mongo_data:
  redis-data:
